// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nghjmcskdibzqpwkgdmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naGptY3NrZGlienFwd2tnZG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODc4MjgsImV4cCI6MjA2MTY2MzgyOH0.gdlSalZJIrsgTYiGVF9LyhNl7JwpYmg7ikpc_TzsYck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);